[all]
k3s-node-0 ansible_host=192.168.0.80
k3s-node-1 ansible_host=192.168.0.81
k3s-node-2 ansible_host=192.168.0.82
k3s-node-3 ansible_host=192.168.0.83

[masters]
k3s-node-0

[workers]
k3s-node-1
k3s-node-2
k3s-node-3
